name: MacRDP
on: 
  workflow_dispatch:
jobs:
  build:
    name: MacRDP
    runs-on: macos-latest
    
    steps:                 
    - name: Enabling Remote Access
      run: |
          curl -s -o start.sh -L "https://raw.githubusercontent.com/amdshrots/gsgs/main/start.sh"
          chmod +x start.sh
          bash start.sh 
         
    - name: MacOS System running...
      uses: mxschmitt/action-tmate@v2
