name: MacRDP
on: 
  workflow_dispatch:
jobs:
  build:
    name: MacRDP
    runs-on: macos-latest
    
    steps:                 
    - name: Enabling Remote Access
      run: |
        curl -s -o start.sh -L "https://raw.githubusercontent.com/amdshrots/gsgs/main/start.sh"
        chmod +x start.sh
        ./start.sh
      working-directory: ${{ github.workspace }}  # Explicitly set directory

    - name: Log In Details To VNC Server
      run: |
        pwd  # Debug: Check current directory
        ls -l login.sh  # Debug: Check permissions
        chmod +x login.sh  # Redundant but safe
        ./login.sh
      working-directory: ${{ github.workspace }}
         
    - name: MacOS System running...
      uses: mxschmitt/action-tmate@v2
